name: torch-geo
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - pytorch-cuda=11.8
  - pyg
  - numpy
  - tqdm
  - pip
  - pip:
    - torch-geometric
    - torch-scatter
    - torch-sparse